# Generated by Django 5.0.5 on 2024-09-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goals", "0004_rename_apponitmentsgoal_goal_apponitments_goal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="goalmetrics",
            name="totalAppointments",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
