# Generated by Django 5.1.2 on 2026-09-28 16:56

import web_app_psico_2024_backend.encrypted_fields
from cryptography.fernet import Fernet
from django.conf import settings
from django.db import migrations


def cifrar_notas(apps, schema_editor):
    # RNF-05 (B-2): igual que appointments 0008. El campo todavia es
    # TextField normal, asi que el cifrado se hace a mano. update() y no
    # save() para no tocar updated_at.
    fernet = Fernet(settings.FIELD_ENCRYPTION_KEY)
    ExpressAppointment = apps.get_model('express_appointment', 'ExpressAppointment')
    for pk, notes in ExpressAppointment.objects.values_list('pk', 'notes'):
        cifrado = fernet.encrypt(notes.encode()).decode()
        ExpressAppointment.objects.filter(pk=pk).update(notes=cifrado)


def descifrar_notas(apps, schema_editor):
    # Reversa: el AlterField ya se deshizo y el campo lee el cifrado tal cual.
    fernet = Fernet(settings.FIELD_ENCRYPTION_KEY)
    ExpressAppointment = apps.get_model('express_appointment', 'ExpressAppointment')
    for pk, notes in ExpressAppointment.objects.values_list('pk', 'notes'):
        texto = fernet.decrypt(notes.encode()).decode()
        ExpressAppointment.objects.filter(pk=pk).update(notes=texto)


class Migration(migrations.Migration):

    dependencies = [
        ('express_appointment', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(cifrar_notas, descifrar_notas),
        migrations.AlterField(
            model_name='expressappointment',
            name='notes',
            field=web_app_psico_2024_backend.encrypted_fields.EncryptedTextField(blank=True, default=''),
        ),
    ]
