# Generated by Django 5.1.2 on 2026-06-02 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('patient', '0001_initial'), ('patient', '0002_patient_address_patient_gender_and_more'), ('patient', '0003_patient_name_of_manager_and_more'), ('patient', '0004_rename_name_of_manager_patient_tutor')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('phone', models.CharField(blank=True, default='', max_length=25)),
                ('age', models.IntegerField()),
                ('place', models.CharField(choices=[('CDO', 'CDO'), ('SEMILLERO', 'Semillero'), ('EXTERNAL', 'Externo')], default='CDO', max_length=50)),
                ('pacientNumber', models.IntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grade', models.TextField(blank=True, default='')),
                ('state', models.BooleanField()),
                ('stateDescription', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='patient',
            name='managers_phone_number',
            field=models.CharField(default=' '),
        ),
        migrations.AlterField(
            model_name='patient',
            name='grade',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_of_manager',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='name_of_manager',
            new_name='tutor',
        ),
    ]
