# Generated by Django 5.1.2 on 2026-06-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_address_patient_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='name_of_manager',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='patient',
            name='managers_phone_number',
            field=models.CharField(default=' '),
        ),
    ]
