# Generated by Django 5.1.2 on 2026-06-02 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_patient_name_of_manager_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='name_of_manager',
            new_name='tutor',
        ),
    ]
