# Generated by Django 5.1.2 on 2026-06-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial_squashed_0004_rename_name_of_manager_patient_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('MASCULINO', 'maculino'), ('FEMENINO', 'femenino'), ('OTRO', 'otro')], default='OTRO', max_length=50),
        ),
    ]
