# Generated by Django 5.1.2 on 2026-06-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_alter_patient_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='pacientNumber',
        ),
        migrations.AddField(
            model_name='patient',
            name='externalId',
            field=models.CharField(default=0, max_length=250),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('MASCULINO', 'masculino'), ('FEMENINO', 'femenino'), ('OTRO', 'otro')], default='OTRO', max_length=50),
        ),
    ]
