# Generated by Django 5.1.2 on 2026-06-03 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_remove_patient_pacientnumber_patient_externalid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='externalId',
            new_name='external_Id',
        ),
    ]
