# Generated by Django 5.1.2 on 2026-08-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_rename_externalid_patient_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='managers_phone_number',
            field=models.CharField(default=' ', max_length=250),
        ),
    ]
