# Generated by Django 5.1.2 on 2026-09-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_patient_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='managers_phone_number',
            field=models.CharField(blank=True, default=' ', max_length=250),
        ),
    ]
