# Generated by Django 5.1.2 on 2026-09-02 20:21

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0011_alter_patient_managers_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_patient_name_ci'),
        ),
    ]
