# Generated by Django 5.1.2 on 2026-09-21 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0013_patientnote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patientnote',
            name='annulled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientnote',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_patient_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientnote',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
