# Generated by Django 5.1.2 on 2026-09-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0014_patientnote_annulled_at_patientnote_edited_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientnote',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
