# Generated by Django 5.1.2 on 2026-09-22 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0016_patient_assigned_psychologist_casereassignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casereassignment',
            old_name='new_spychologist',
            new_name='new_psychologist',
        ),
    ]
