# Generated by Django 5.1.2 on 2026-09-26 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0018_consenttextversion_patientconsent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientconsent',
            old_name='updated_at',
            new_name='uploaded_at',
        ),
        migrations.RenameField(
            model_name='patientconsent',
            old_name='updated_by',
            new_name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='patientconsent',
            name='uploaded_file',
        ),
        migrations.AlterField(
            model_name='patientconsent',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientconsent',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('SIGNED', 'Firmado y resguardado')], default='PENDING', max_length=20),
        ),
    ]
