# Generated by Django 5.1.2 on 2026-09-27 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0019_consent_status_uploaded_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientconsent',
            name='file_content_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='patientconsent',
            name='file_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientconsent',
            name='file_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
