# Generated by Django 5.1.2 on 2026-09-28 01:35

from django.db import migrations, models


def mark_signed_patients(apps, schema_editor):
    # Antes de borrar PatientConsent.status, los pacientes que ya tenian un
    # escaneado firmado quedan con el nuevo check marcado.
    Patient = apps.get_model('patient', 'Patient')
    Patient.objects.filter(consents__status='SIGNED').update(consent_signed=True)


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0020_patientconsent_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='consent_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(mark_signed_patients, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='patientconsent',
            name='status',
        ),
    ]
