# Generated by Django 5.1.2 on 2026-09-28 16:56

import web_app_psico_2024_backend.encrypted_fields
from cryptography.fernet import Fernet
from django.conf import settings
from django.db import migrations

# RNF-05 (B-2): campos de texto con contenido clinico que pasan a
# guardarse cifrados. El escaneado del consentimiento (bytes) va aparte.
CAMPOS_TEXTO = [
    ('CaseReassignment', 'reason'),
    ('Patient', 'stateDescription'),
    ('PatientNote', 'content'),
]


def _convertir(apps, convertir_texto, convertir_bytes):
    # update() y no save(): no pasa por Patient.save() ni cambia fechas.
    for model_name, campo in CAMPOS_TEXTO:
        Model = apps.get_model('patient', model_name)
        for pk, valor in Model.objects.values_list('pk', campo):
            Model.objects.filter(pk=pk).update(**{campo: convertir_texto(valor)})

    PatientConsent = apps.get_model('patient', 'PatientConsent')
    escaneados = PatientConsent.objects.filter(file_data__isnull=False)
    for pk, datos in escaneados.values_list('pk', 'file_data'):
        PatientConsent.objects.filter(pk=pk).update(
            file_data=convertir_bytes(bytes(datos)))


def cifrar(apps, schema_editor):
    # Aqui los campos todavia son TextField/BinaryField normales (los
    # AlterField van despues), asi que el cifrado se hace a mano.
    fernet = Fernet(settings.FIELD_ENCRYPTION_KEY)
    _convertir(
        apps,
        lambda texto: fernet.encrypt(texto.encode()).decode(),
        fernet.encrypt,
    )


def descifrar(apps, schema_editor):
    # Reversa: los AlterField ya se deshicieron y los campos leen el
    # cifrado tal cual.
    fernet = Fernet(settings.FIELD_ENCRYPTION_KEY)
    _convertir(
        apps,
        lambda texto: fernet.decrypt(texto.encode()).decode(),
        fernet.decrypt,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0021_patient_consent_signed'),
    ]

    operations = [
        migrations.RunPython(cifrar, descifrar),
        migrations.AlterField(
            model_name='casereassignment',
            name='reason',
            field=web_app_psico_2024_backend.encrypted_fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='stateDescription',
            field=web_app_psico_2024_backend.encrypted_fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='patientconsent',
            name='file_data',
            field=web_app_psico_2024_backend.encrypted_fields.EncryptedBinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientnote',
            name='content',
            field=web_app_psico_2024_backend.encrypted_fields.EncryptedTextField(),
        ),
    ]
