# Generated by Django 5.1.2 on 2026-10-01 01:03

from django.db import migrations, models
from django.db.models import Max


def llenar_ultima_atencion(apps, schema_editor):
    # RNF-07: los pacientes que ya tenian citas atendidas quedan con su
    # fecha. Misma regla que Patient.refresh_last_attention_date, copiada
    # aqui porque los modelos de una migracion no tienen sus metodos.
    Patient = apps.get_model('patient', 'Patient')
    Appointment = apps.get_model('appointments', 'Appointment')
    ultimas = (
        Appointment.objects.filter(status='DONE', is_active=True)
        .values('patient_id')
        .annotate(last=Max('date'))
    )
    for fila in ultimas:
        Patient.objects.filter(pk=fila['patient_id']).update(
            last_attention_date=fila['last'])


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0022_rnf05_cifrar_contenido_clinico'),
        ('appointments', '0008_rnf05_cifrar_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='last_attention_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(llenar_ultima_atencion, migrations.RunPython.noop),
    ]
