# Generated by Django 5.1.2 on 2026-06-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
        ('patient', '0007_rename_externalid_patient_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='patients',
            field=models.ManyToManyField(related_name='activiti', to='patient.patient'),
        ),
    ]
