# Generated by Django 5.1.2 on 2026-09-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_activity_start_end_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='time_block',
            field=models.CharField(blank=True, choices=[('08:00', '08:00 - 08:40'), ('08:40', '08:40 - 09:20'), ('09:20', '09:20 - 10:00'), ('10:00', '10:00 - 10:40'), ('10:40', '10:40 - 11:20'), ('11:20', '11:20 - 12:00'), ('12:00', '12:00 - 12:40'), ('12:40', '12:40 - 13:20')], default='', max_length=5),
        ),
    ]
