# Generated by Django 5.1.2 on 2026-06-02 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('appointments', '0001_initial'), ('appointments', '0002_appointment_goal_alter_appointment_status'), ('appointments', '0003_appointment_place'), ('appointments', '0004_appointment_notes')]

    dependencies = [
        ('patient', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.TimeField()),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DONE', 'Hecho'), ('PENDING', 'Pendiente'), ('CANCELLED', 'Cancelado')], default='DONE', max_length=50)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment', to='patient.patient')),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('DONE', 'Hecho'), ('PENDING', 'Pendiente'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=50),
        ),
        migrations.AddField(
            model_name='appointment',
            name='place',
            field=models.CharField(choices=[('CDO', 'CDO'), ('SEMILLERO', 'Semillero'), ('OTHER', 'Otro')], default='CDO', max_length=50),
        ),
        migrations.AddField(
            model_name='appointment',
            name='notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
