# Generated by Django 5.0.5 on 2024-06-09 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("DONE", "Hecho"),
                    ("PENDING", "Pendiente"),
                    ("CANCELLED", "Cancelado"),
                ],
                default="PENDING",
                max_length=50,
            ),
        ),
    ]
