# Generated by Django 5.1.2 on 2025-07-29 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_appointment_goal_alter_appointment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="place",
            field=models.CharField(
                choices=[("CDO", "CDO"), ("SEMILLERO", "Semillero"), ("OTHER", "Otro")],
                default="CDO",
                max_length=50,
            ),
        ),
    ]
