# Generated by Django 5.1.2 on 2025-07-29 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0003_appointment_place"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="notes",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
