# Generated by Django 5.1.2 on 2026-09-28 16:56

import web_app_psico_2024_backend.encrypted_fields
from cryptography.fernet import Fernet
from django.conf import settings
from django.db import migrations


def cifrar_notas(apps, schema_editor):
    # RNF-05 (B-2): cifra las notas que ya existen. Aqui el campo todavia
    # es TextField normal (el AlterField va despues), asi que lee y
    # escribe el texto tal cual: el cifrado se hace a mano. update() y no
    # save() para no tocar updated_at.
    fernet = Fernet(settings.FIELD_ENCRYPTION_KEY)
    Appointment = apps.get_model('appointments', 'Appointment')
    for pk, notes in Appointment.objects.values_list('pk', 'notes'):
        cifrado = fernet.encrypt(notes.encode()).decode()
        Appointment.objects.filter(pk=pk).update(notes=cifrado)


def descifrar_notas(apps, schema_editor):
    # Reversa: el AlterField ya se deshizo, asi que el campo vuelve a ser
    # TextField y lee el texto cifrado tal cual.
    fernet = Fernet(settings.FIELD_ENCRYPTION_KEY)
    Appointment = apps.get_model('appointments', 'Appointment')
    for pk, notes in Appointment.objects.values_list('pk', 'notes'):
        texto = fernet.decrypt(notes.encode()).decode()
        Appointment.objects.filter(pk=pk).update(notes=texto)


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_appointment_time_block'),
    ]

    operations = [
        migrations.RunPython(cifrar_notas, descifrar_notas),
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=web_app_psico_2024_backend.encrypted_fields.EncryptedTextField(blank=True, default=''),
        ),
    ]
